Cyra
hytech-racing/Software-Onboarding-2025 pull request #29
Opened 2024-09-01 20:00 UTC by cyraalesha

Added lab 2. Not sure if the flake is entirely correct but it seems to build successfully and created a flake.lock

2024-09-03 04:37 UTC, RCMast3r requested changes
it doesnt loo

2024-09-03 04:37 UTC, RCMast3r commented on Cyra/lab2/CMakeLists.txt
> +include_directories(include)
do not use include_directories, only use target_include_directories and include directories per each target, not globally within a cmakelists

2024-09-03 04:37 UTC, RCMast3r commented on Cyra/lab2/CMakeLists.txt
> +add_library(hellolib SHARED src/hellolib.cpp)
this doesnt appear to be the correctly named source file, cmake is case-sensitive for these file names

2024-09-03 04:37 UTC, RCMast3r commented on Cyra/lab2/CMakeLists.txt
> +
where is your install phase for lab2? this is required by nix

2024-09-03 04:37 UTC, RCMast3r commented on Cyra/lab2/flake.nix
> +}
this flake is missing a proper use of nix packages, see:

https://github.com/nixvital/nix-based-cpp-starterkit/blob/main/flake.nix

2024-09-05 14:48 UTC, cyraalesha commented
Updated

2024-09-05 19:05 UTC, RCMast3r approved these changes

2024-09-05 20:28 UTC, merged