Lab 1
hytech-racing/Software-Onboarding-2025 pull request #30
Opened 2024-09-01 21:10 UTC by mileskent

Testing my ability to create a PR + finished lab 1 to my understanding

2024-09-01 23:41 UTC, RCMast3r requested changes

2024-09-01 23:41 UTC, RCMast3r commented on milesK/milesKlab1/.gitignore
Please use the top level .gitignore

2024-09-02 00:04 UTC, mileskent commented on milesK/milesKlab1/.gitignore
It adjusted it.

2024-09-03 05:09 UTC, RCMast3r commented
@mileskent pls re-request my review next time so that I get notified to take a look back at it <3

![image](https://github.com/user-attachments/assets/66ff3c28-c9b3-4bf7-aa01-8513b7e9681e)

2024-09-03 05:11 UTC, RCMast3r approved these changes

2024-09-03 13:08 UTC, closed without merging