Lab2 part 1
hytech-racing/Software-Onboarding-2025 pull request #39
Opened 2024-09-02 03:44 UTC by goltsmannn

2024-09-02 15:29 UTC, RCMast3r requested changes

2024-09-02 15:29 UTC, RCMast3r commented on goltsmannn2/default.nix
> +  src = "CMakeLists.txt";
this should just be the relative path to your source code, not just a single source:

https://blog.ielliott.io/nix-docs/mkDerivation.html

2024-09-02 15:29 UTC, RCMast3r commented on goltsmannn2/CMakeLists.txt
you need to have an install step for your binary as the installed files are what nix actually copies to its nix store path

https://cmake.org/cmake/help/latest/command/install.html

2024-09-02 15:29 UTC, RCMast3r commented on goltsmannn2/default.nix
> +  src = "CMakeLists.txt";
more docs here: https://github.com/NixOS/nixpkgs/blob/master/doc/stdenv/stdenv.chapter.md

2024-09-02 15:29 UTC, RCMast3r commented on goltsmannn2/flake.nix
> +        };
this is a good flake! except for one thing which is we should prefer to support multiple system types per flake:

you can do this following this blog post's outline
https://ayats.org/blog/no-flake-utils

2024-09-05 01:54 UTC, goltsmannn commented
Fixed everything

2024-09-05 01:58 UTC, RCMast3r approved these changes

2024-09-05 20:28 UTC, merged