Completed Lab 2 Part 2
hytech-racing/Software-Onboarding-2025 pull request #74
Opened 2024-09-12 23:49 UTC by goltsmannn

2024-09-13 21:40 UTC, RCMast3r requested changes

2024-09-13 21:40 UTC, RCMast3r commented on goltsmannn2/.gitignore
please use the parent, top-level .gitignore, dont include your own

2024-09-13 21:40 UTC, RCMast3r commented on goltsmannn2/part1/result
please dont push your result symlink file

2024-09-14 01:26 UTC, goltsmannn commented
Fixed and pushed commits

2024-09-14 04:57 UTC, RCMast3r approved these changes

2024-09-14 05:46 UTC, merged